packages:
    - fixtures/*
    - packages/*

catalogs:
    dev:
        tsdown: ^0.15.7
    framework:
        "@types/react": ^18.3.1
        "@types/react-dom": ^18.3.1
        lit: ^3.2.0
        preact: ^10.26.0
        react: ^18.3.1
        react-dom: ^18.3.1
        solid-js: ^1.9.3
        svelte: ^5.0.0
        vue: ^3.5.0
    plugins:
        "@builder.io/qwik": ^1.17.2
        "@sveltejs/vite-plugin-svelte": ^6.2.1
        "@vitejs/plugin-react": ^5.1.0
        "@vitejs/plugin-vue": ^6.0.1
        unplugin-dts: ^1.0.0-beta.6
        vite-plugin-solid: ^2.11.10
    tools:
        "@prettier/plugin-oxc": ^0.0.4
        "@typescript/native-preview": latest
        prettier: ^3.6.2
        prettier-plugin-pkg: ^0.21.2
        prettier-plugin-svelte: ^3.3.7
        prettier-plugin-toml: ^2.0.6
        vite: "^6.0.0 || ^7.0.0"

onlyBuiltDependencies:
    - esbuild
    - sharp
    - unrs-resolver
